// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBfqGk_JUx5t1Aj2H4vGIk3yRSbY2UkV0',
    appId: '1:25675889394:android:9ee3c23f3eb15e852bae6b',
    messagingSenderId: '25675889394',
    projectId: 'fundipap-global',
    storageBucket: 'fundipap-global.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjnsYDSfupv3mS5L7PAnJ9dh95sdOHz4',
    appId: '1:25675889394:ios:b19620dcb6f39c782bae6b',
    messagingSenderId: '25675889394',
    projectId: 'fundipap-global',
    storageBucket: 'fundipap-global.firebasestorage.app',
    iosBundleId: 'com.example.fundipap',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjnsYDSfupv3mS5L7PAnJ9dh95sdOHz4',
    appId: '1:25675889394:ios:b19620dcb6f39c782bae6b',
    messagingSenderId: '25675889394',
    projectId: 'fundipap-global',
    storageBucket: 'fundipap-global.firebasestorage.app',
    iosBundleId: 'com.example.fundipap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk4qqt4g6zU0Xfucp8uIvcdljFhiY-FSA',
    appId: '1:25675889394:web:7dd4c0ac3b0a607a2bae6b',
    messagingSenderId: '25675889394',
    projectId: 'fundipap-global',
    authDomain: 'fundipap-global.firebaseapp.com',
    storageBucket: 'fundipap-global.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk4qqt4g6zU0Xfucp8uIvcdljFhiY-FSA',
    appId: '1:25675889394:web:7dd4c0ac3b0a607a2bae6b',
    messagingSenderId: '25675889394',
    projectId: 'fundipap-global',
    authDomain: 'fundipap-global.firebaseapp.com',
    storageBucket: 'fundipap-global.firebasestorage.app',
  );
}
